### ISSUE TITLE
Create basic AR scene

### ISSUE THREAD

**Issue by sagarreddypatil** [InVisionAR/ar-app#3]
Create a basic Unity scene with AR which allows you to drop boxes onto a floor. Use old repository as reference: https://github.com/sagarreddypatil/InVisionAR

The old repo is very messy, so feel free to ask any questions you have.

**Comment by Bwoltz** [comment]
I'm afraid to say I'll give this a shot because Unity is still new to me, but it sounds interesting so... I'll give it a shot?

**Comment by Abh1T** [comment]
if not done before October 2nd, I am more than happy to work on this one too

**Comment by PragathSiva** [comment]
I will try to work on this task. Unity is very new to me so I will try my best.

**Comment by Abh1T** [comment]
i will start working on this task
